version: '3'

tasks:
  test:
    desc: "Run the test for all packages and subpackages"
    cmds:
      - go test ./...

  test-verbose:
    desc: "Run the test for all packages and subpackages with verbose output"
    cmds:
      - go test -v ./...

  release:
    desc: "Run a standard release from develop to main using git flow"
    cmds:
      - npx --yes entro-version release --main-branch-name=main