name: "Testing"

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      
      - name: Display go version
        run: go version

      - name: Install dependencies
        run: task install-deps

      - name: Build the binary
        run: task build-binary

      - name: Run tests
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TEST_IMAGE_NAME: ${{ vars.TEST_IMAGE_NAME }}
        run: task test-verbose
